### ISSUE TITLE
http://sketchup.github.io/ruby-api-docs/

### ISSUE THREAD

**Issue by MSP-Greg** [SketchUp/ruby-api-docs#1]
So, not quite public yet?

Then there's ChrisFullmer/project_up?

Greg MSP-Greg

**Comment by thomthom** [comment]
@ChrisFullmer 's project was just a test to learn how GitHub Pages work. This will be the main repo. We still have some work to do before we can announce it.

This initial release will be mainly about getting existing docs migrated to YARD and the new backend. There are lots of general improvements that can be made, but the old system was so fragile and required too much manual work to update that it was hindering us.

Once we get everything migrated we can look at improving the content.
