### ISSUE TITLE
UI::ActionCallbackContext - add description or note

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/ruby-api-docs#14]
Add a description or note for class **`UI::ActionCallbackContext`**, even if it's is simply along the lines of:

"_This class is for internal use by the application and therefor this class has no developer usable features._"

This at least will (hopefully) prevent the need for questions like:
[**SketchUp forums**: No document to UI::ActionCallbackContext](http://forums.sketchup.com/t/no-document-to-ui-actioncallbackcontext/34160)

**Comment by thomthom** [comment]
Ah! That one slipped through. We meant to add a note that this is currently just acting as a placeholder. The feature didn't get completed, but we needed to have the class in place in order to avoid making breaking changes when it's hooked up.

**Comment by DanRathbun** [comment]
Okay, so this class no longer shows in the online docs. 
Does that make need for this issue to be closed ?
