### ISSUE TITLE
favicon.ico missing

### ISSUE THREAD

**Issue by MSP-Greg** [SketchUp/ruby-api-docs#25]
Maybe drop one in the repo root?

**Comment by DanRathbun** [comment]
I see it in both my Chrome tabs and bookmark link menus.
In the **`<head>`** of the document is this element:
```html
<link rel="shortcut icon" type="image/vnd.microsoft.icon"
 href="https://help.sketchup.com/sites/all/themes/sketch_help/favicon.ico">
```
---

What would be the **purpose** of actually including the icon file **within** the repo ?

**Comment by MSP-Greg** [comment]
Fixed.

@DanRathbun

> What would be the purpose of actually including the icon file within the repo ?

Old web 'standard'.

http://ruby.sketchup.com/ <=> https://sketchup.github.io/ruby-api-docs/
