### ISSUE TITLE
"Generated on" Footer

### ISSUE THREAD

**Issue by jimfoltz** [SketchUp/ruby-api-docs#26]
Could the "Generated On" footer by kept to a single file so it does not touch every file html file in the repo? It's hard to find what actually changed when all the files have changed due to the generation date being updated.

**Comment by MSP-Greg** [comment]
Lose the footer date-time and maybe put a rev date in the SU/Trimble header?

templates\default\layout\html\footer.erb

**Comment by thomthom** [comment]
Yea, the timestamp have bothered me as well. Not sure how we can insert it to only one page. It's doable somehow, but tracing hiw the template work is convoluted. I wad tempted at removing it all together.

Greg, moving the tomestamp from the footer to the header doesn't change anything, all the erb files get compiled to single html files.

**Comment by jimfoltz** [comment]
`iframe`? The side-bar is an `iframe` using the `class_list.html` as its source.

**Comment by jimfoltz** [comment]
I will play with the template and see what works.  I think an `iframe` should work using some generatde `footer.html` file as its source.

**Comment by thomthom** [comment]
Is the timestamp that useful/important though?

**Comment by thomthom** [comment]
The git repo got timesyamps for the particularly interested.

**Comment by jimfoltz** [comment]
> Is the timestamp that useful/important though?

No. I figured it was something you wanted.

**Comment by thomthom** [comment]
Nah, it was part of the default template.
I think I'll just strip it out.

**Comment by MSP-Greg** [comment]
@thomthom 

> doesn't change anything, all the erb files get compiled to single html files.

Missed that, sorry.  Thought maybe it was an iframe.

You could use an iframe for the header or open the css file and use :after content to change it in the header...

**Comment by thomthom** [comment]
I'm not a fan of iframe. Adds extra HTTP requests - for a timestamp its not worth it. Frames in genetal is discouraged in moders webdesign.

**Comment by MSP-Greg** [comment]
FYI, I striped it out so my commits would involve just the changed files, main 'home' page shows when the library was last updated.

Speaking of, thought about adding the Ruby library in current SU version?  IOW, site would have the SU API docs and the Ruby docs...
