### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by MSP-Greg** [SketchUp/ruby-api-docs#3]
Having had a recent discussion with Thom about index...

You're probably aware of this, if not, this might save someone some trouble...

GitHub.io will not respond to a filename request beginning with an underscore. Hence, _index.html, which is linked to by all pages, will give a 404.

In yard-t2, I took care of that in app.js, (the event handler for the 'menu' or object path), but you're not using that right now...

**Comment by thomthom** [comment]
Hm... Are the some dead links when viewing them on GitHub pages?

**Comment by MSP-Greg** [comment]
Thom,

![image](https://cloud.githubusercontent.com/assets/15081176/14589854/204c74f8-04b2-11e6-8f88-53c4b48a69be.png)

The index links, (shown as 'Index (S)' in image)

As I mentioned, somewhat specific to GitHub.io

**Comment by DanRathbun** [comment]
> The index links, (shown as 'Index (S)' in image)

I do **not** know why, but these index links **do** work for the pages accessed via **ruby.sketchup.com**.

Is this still an issue that needs to remain open ?

**Comment by MSP-Greg** [comment]
Dan,  thanks for checking, I’ll close
