### ISSUE TITLE
Update Announcements on Forum?

### ISSUE THREAD

**Issue by jimfoltz** [SketchUp/ruby-api-docs#40]
Might there be a way to automatically create a forum posting when this repo is updated?  Maybe have a dedicated topic for doc updates.  It might be good for folks to see improvements being made. I know GitHub as a large list of hooks - I haven't looked into them yet.  

Or maybe a Dev blog post on commit, even though the SketchUp blogs seem geared more towards larger, in-depth postings.  It might breath some life back to the dev blog.

**Comment by jimfoltz** [comment]
Nice idea maybe, but who has time.

**Comment by DanRathbun** [comment]
I actually like the idea of being notified when edits are pushed.
I'm watching the repo, so I wonder if I'll see when Thomas makes the next commit ?
