### ISSUE TITLE
Entities#add_circle return value on failure

### ISSUE THREAD

**Issue by jimfoltz** [SketchUp/ruby-api-docs#42]
The docs should say what the return values is upon failure to add a circle.

**Comment by DanRathbun** [comment]
It is not likely this will get fixed unless you open an issue in the stubs tracker.
https://github.com/SketchUp/ruby-api-stubs

**Comment by jimfoltz** [comment]
I guess I can’t keep track.  There are 3 repos that would appear to be acceptable.

**Comment by thomthom** [comment]
Sorry for the confusion - I can add a GitHub issue template that makes it clearer.

**Comment by jimfoltz** [comment]
No that’s alright.  I was on a phone which doesn’t provide the overview and quick navigation you get when using a desktop browser.
