### ISSUE TITLE
collapse button for method listing doesn't work

### ISSUE THREAD

**Issue by thomthom** [SketchUp/ruby-api-docs#5]
This worked recently. Not sure what broke it.

**Comment by MSP-Greg** [comment]
app.js is needed for collapse / expand

gh-pages branch **does not** have app.js
[https://github.com/SketchUp/ruby-api-docs/tree/gh-pages/js](https://github.com/SketchUp/ruby-api-docs/tree/gh-pages/js)

master branch **does** have app.js
[https://github.com/SketchUp/ruby-api-docs/tree/master/js](https://github.com/SketchUp/ruby-api-docs/tree/master/js)

**Comment by thomthom** [comment]
@MSP-Greg - you are too fast for me! Thanks for making my life easier. Now I can jump straight to the fix. :)
