### ISSUE TITLE
Milestones for the 2017 "official" API release and other goals

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/ruby-api-docs#9]
Please set and close a Milestone for the 2017 "official" API release of the YARD driven docs.

Can anyone think of other milestones to work toward ?

**Comment by thomthom** [comment]
Why create and close an empty milestone?

Milestones is for organising open issues.

**Comment by thomthom** [comment]
If this issue is to have some sort of marker to reflect SketchUp releases then we can add a tag - that would follow the git repo if you pull it.

**Comment by DanRathbun** [comment]
> Milestones _are_ for _organizing_ open issues.

True, and there should have been one open for the inaugural release of the YARD API docs.

> Why create and close an empty milestone?

(1) Because later it will look strange when you don't have milestone 1, but do have obviously later milestones.

... and (2) because you can assign the 3 issues you closed last April, and the recent commits to this "initial" milestone.

**Comment by DanRathbun** [comment]
> If this issue is to have some sort of marker to reflect SketchUp releases ...

**No not exactly.** (But you CAN create release specific milestones, to assign the bulk of changes in November to, in each cycle.)

There can also be other milestones in the intervals between major releases. 

An example is the large job to correctly indicate method return types. It would be smart to slice up this job into smaller milestones. So, for instance, you could create a milestone that acknowledges the completion of all `Geom` module class methods and the methods of it's wrapped classes. Another for the `UI` module. etc. etc.

**Comment by thomthom** [comment]
So far we tracked things internally - but it might make sense to move it here. Need to check with team/manager. I'm not sure if we want this issue tracker to be mainly a way for users to report issues.

**Comment by DanRathbun** [comment]
It may be that you also track things internally (like every other SketchUp family product,) but keep in mind that the API(s) and their docs are a product, and the developers are the consumers. So for the purpose here, milestones are a "signal" to the developers using/reading this tracker, that the docs are being maintained, and that work is progressing.

So it would be a courtesy to the developers. The devs are giving feedback, and y'all should respond in kind, by giving reverse feedback.

Anyway, this comes from my philosophy, .. it's just an idea. Use it or not. (I thought, hey the feature is there, why not use it?)

**Comment by DanRathbun** [comment]
*And for reference, see the GitHub chapter on use of milestones:*
https://help.github.com/articles/tracking-the-progress-of-your-work-with-milestones/

**Comment by DanRathbun** [comment]
I seems that this idea has been rejected. If so, then we may as well close it.

?

**Comment by DanRathbun** [comment]
Closing this as I think this is also the wrong repo for this issue.

Ie, this repo just serves the html doc pages at **ruby.sketchup.com**.

It would be better for doc issues to be filed under the [api-issue-tracker](https://github.com/SketchUp/api-issue-tracker) repo.
